{% set name = "pytest-fixture-config" %}
{% set version = "1.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c739895fe20851bdba53f246d0599aa389bc1a1cba48db2ecac0130576dc1b0e

build:
  number: 0
  script: "python -m pip install --no-deps --ignore-installed ."
  noarch: python

requirements:
  host:
    - pip
    - pytest
    - python
    - setuptools
    - setuptools-git
  run:
    - pytest
    - python

test:
  imports:
    - pytest_fixture_config
  requires:
    - pytest
    - six

about:
  home: https://github.com/manahl/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: Fixture configuration utils for py.test
  doc_url: https://github.com/manahl/pytest-plugins/tree/master/pytest-fixture-config#readme
  dev_url: https://github.com/manahl/pytest-plugins

extra:
  recipe-maintainers:
    - jcfr
