travis:
  secure:
    BINSTAR_TOKEN: jEe1i1nmjH8ACTv5fDdtae4R10BCv/JlgzApyuWNgq+RbG36rByC8VPiKKyOpaaRiX+6SMqImBOufZ9gPOWMrv8pC4TonxI74PNalvCuHE+DtUIgXDBF9BejbmhNHuUKDVP4sL5SmIbRaF24aqSd/mRbj81J8xrD5NDRnzkAjrLEeCDF7nbH7a/+2tiw78fWkBlQDXBCm7hqLYH6+hsB+EHALhzMG+duz5uyElBU2Ym+QiAwiuWDvNWP1Y7SSaobFh7dA0wgXIR12eQELNdPyBByrCm+ctO70tXFMtWlGrVSpHcHCkgmfGU6AigMJ+B1PjZJtVPerTFQtB3WC+9cBppVkCM/R+DIxoEdC/kKYLVCrgY4mAc/r5i2e/5zg0AAfHi7F9u/rdCQCC98x5D4RwI21fxht8Bawmhui9/m4zKhZu9Xx33wQ7mGZvz5FUF8yBKK5Gut31Uu3dENiem4DkmCi1fMW/caX3mhy14FXUD1QHLLVjauJCAecRkup1xAqxpPbwYcJ91SY/uNOEDwmgMv+CacmFVW2IXofNX0w8okgg/6RS8eVxoMWuTgpl/E9G5fL/x8FSPL6D7qME6i2ns9/vJeIxdS0qaxzfADvJoKvv6cvYATdNSObLc7bKROHMjQr4EVWx/ends//h10zZqF3fu4QI1RBdtbVfhOSTE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
